### ISSUE TITLE
Massiveconomy

### ISSUE THREAD

**Issue by SoyBueno** [EvolSoft/MassiveEconomy#1]
There is a bug with simpleauth because i download and i dont have peemission to command /login.please help me and fix this bug.massiveconomy cause this with the plugin simpleauth

**Comment by Flavius12** [comment]
MassiveEconomy doesn't manage other plugin permissions. I noticed this problem but it's not related to MassiveEconomy but to PocketMine or SimpleAuth itself

**Comment by SoyBueno** [comment]
Thanks
